apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebind2
  namespace: namespace2
subjects:
- kind: ServiceAccount
  name: daniel
  namespace: namespace2
roleRef:
  kind: Role 
  name: role1