apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebind1
  namespace: namespace1
subjects:
- kind: ServiceAccount
  name: artjom
  namespace: namespace1
roleRef:
  kind: Role 
  name: role1